engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- config/**/*
#add comment to test PR integration
